Add reviews
Keindel/java-filmorate pull request #10
Opened 2022-06-28 20:08 UTC by aBoyarov

2022-06-30 09:02 UTC, Keindel requested changes
Спасибо за труд! Уффф много!)
Постарался все внимательно посмотреть.
Все очень хорошо! Пользуясь этой возможностью практики ревью, позволил себе оставить несколько предложений об изменениях.)

2022-06-30 09:07 UTC, aBoyarov commented on src/main/resources/schema.sql
> +        foreign key (film_id) references films(film_id)
А на мой легче делать ограничения после полей

2022-06-30 09:08 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +                -> rs1.getLong("user_id"), rs.getLong("review_id")));
Так больше классический метод напоминает, сверху входные параметры, внизу тело

2022-06-30 09:08 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        clearAllLikesAndDislikesByPosts(review);
Согласен, переделаю

2022-06-30 09:09 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +                "                    content = ?," +
Плюсую, переделаю)

2022-06-30 10:56 UTC, Keindel commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @EqualsAndHashCode.Include
Вопрос в том почему аннотация @EqualsAndHashCode.Include над полем useful?

2022-06-30 11:17 UTC, Keindel commented on src/main/resources/schema.sql
> +        foreign key (film_id) references films(film_id)
ок

2022-06-30 12:31 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @EqualsAndHashCode.Include
А я сам хз как она работает, убрал и ничего не изменилось, поэтому пожалуй так и оставлю, сортировка при возврате у меня в любом случае написана

2022-06-30 12:31 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +                "                    content = ?," +
Готово

2022-06-30 15:52 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +                -> rs1.getLong("user_id"), rs.getLong("review_id")));
Да я перенесу если тебе это так важно

2022-06-30 19:45 UTC, Keindel approved these changes

2022-06-30 19:46 UTC, Keindel approved these changes

2022-07-02 09:23 UTC, kompasvideo commented
Критических замечаний нет )

2022-07-02 09:32 UTC, kompasvideo approved these changes

2022-07-02 09:32 UTC, kompasvideo commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        return new Review(rs.getLong("review_id"),
Можно использовать аннотацию @Builder для класса Review, тогда и конструктор вызывать не надо. но и так всё ок

2022-07-02 09:32 UTC, kompasvideo commented on src/main/resources/schema.sql
> +(
мне больше нравиться написание как в практикуме - КЛЮЧЕВЫЕ СЛОВА БОЛЬШИМИ БУКВАМИ, переменные - маленькими

2022-07-02 10:55 UTC, merged