feat: search common films
Keindel/java-filmorate pull request #13
Opened 2022-06-29 16:25 UTC by aBoyarov

2022-06-30 06:55 UTC, Keindel requested changes

2022-06-30 06:55 UTC, Keindel commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        userLikesFilms.retainAll(friendLikesFilms);
Вот это прикольно, что используется готовый метод коллекции, не знал о нем.)

2022-06-30 06:55 UTC, Keindel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sqlGetFilmForLikes = "SELECT f.film_id, f.name, f.description, f.release_date, f.duration, f.mpa_id, mpa.name " +
Если совсем уж придираться, то для читаемости может название переменной сделать sqlGetFilmsForUser, а еще понятнее как в методе - sqlGetAllFilmsWithLikesFromUser? то же самое чуть короче: sqlGetFilmsLikedByUser

2022-06-30 07:06 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sqlGetFilmForLikes = "SELECT f.film_id, f.name, f.description, f.release_date, f.duration, f.mpa_id, mpa.name " +
+

2022-06-30 07:17 UTC, Keindel approved these changes

2022-07-01 09:45 UTC, Rexsus-bit commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getCommonFilms(@RequestParam Long userId, @RequestParam Long friendId) throws UserNotFoundException {
Для единообразия с остальными методами можно использовать возвращаемый тип Collection<Film>

2022-07-01 10:02 UTC, Rexsus-bit approved these changes

2022-07-01 12:02 UTC, aBoyarov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getCommonFilms(@RequestParam Long userId, @RequestParam Long friendId) throws UserNotFoundException {
Согласен

2022-07-01 13:03 UTC, Rexsus-bit approved these changes

2022-07-02 07:39 UTC, merged