Sprint 1
Keindel/java-filmorate pull request #4
Opened 2022-05-06 10:56 UTC by Keindel

2022-05-06 12:20 UTC, eugene-lenkevich requested changes
Привет, спасибо, есть несколько моментов :)

2022-05-06 12:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +//import lombok.NonNull;
Это незачем оставлять, только засоряет :)

2022-05-06 12:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
private не забываем :)

PS
Тут, кстати, можно использовать ConcurrentHashMap. Web - конкурентная среда по определению. fyi

https://habr.com/ru/post/132884/

2022-05-06 12:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +//                film == null
Опять таки, лучше почистить :)

2022-05-06 12:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    Map<Integer, User> users = new HashMap<>();
private

2022-05-06 12:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +//        if (user == null
:)

2022-05-06 12:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmValidationException.java
> +public class FilmValidationException extends Throwable {
Давай все таки наследоваться от Exception,  будут ждать именно этот класс :)

2022-05-06 12:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
А зачем id то исключать, вообще лучше только по id все и считать :)

2022-05-06 12:50 UTC, Keindel commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
приходят (по крайней мере в тестах авторов) без id и получается, что добавляется дублирующий объект, т.к. сравнение считает их разными

2022-05-06 18:54 UTC, Keindel commented
Учел комментарии.

2022-05-07 03:17 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-05-07 08:38 UTC, merged